# -*- coding: utf-8 -*-
"""CodeAlpha_Data_science/Iris Flower Classification Using Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2bPMosHqyeJhjKX_Gih7uVSR0YwGUht
"""

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# ====================== LOAD DATASET ======================
# Load Iris dataset
df = pd.read_csv("Iris.csv")

# Convert to Pandas DataFrame for better readability
iris = load_iris() # Ensure iris dataset is loaded to access its attributes
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target

# Map target numbers to species names
df['species_name'] = df['species'].map({
    0: 'setosa',
    1: 'versicolor',
    2: 'virginica'
})

print("=== Dataset Overview ===")
print(df.head())
print(f"\nDataset Shape: {df.shape}")
print("\nTarget Distribution:")
print(df['species_name'].value_counts())

# ====================== PREPARE FEATURES & TARGET ======================
X = df[iris.feature_names]      # Features
y = df['species']               # Target

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

print(f"Training samples: {X_train.shape[0]}")
print(f"Testing samples: {X_test.shape[0]}")

# ====================== TRAIN MODEL ======================
# Initialize Random Forest with some hyperparameters
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=6,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

# ====================== MAKE PREDICTIONS ======================
y_pred = model.predict(X_test)

# ====================== EVALUATE MODEL ======================
accuracy = accuracy_score(y_test, y_pred)

print("\n" + "="*50)
print(f"Model Accuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")
print("="*50)

print("\nClassification Report:")
print(classification_report(y_test, y_pred,
                          target_names=iris.target_names))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=iris.target_names,
            yticklabels=iris.target_names)
plt.title('Confusion Matrix - Iris Classification')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# ====================== FEATURE IMPORTANCE ======================
feature_importance = pd.DataFrame({
    'Feature': iris.feature_names,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("\nFeature Importance:")
print(feature_importance)

# Plot Feature Importance
plt.figure(figsize=(10, 6)) # Completed the figsize tuple
sns.barplot(x='Importance', y='Feature', data=feature_importance)
plt.title('Feature Importance for Iris Classification')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()